name: "Workflow Practice"
on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'  # Runs every day at midnight UTC  
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name : Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: latest
    #   - name: Install dependencies #modified to npm ci from npm install for faster and more reliable builds by Vanshal Kasera
    #     run: npm ci
    #   - name: Run tests
    #     run: npm test
    #   - name: print message
    #     run: echo "Workflow practice completed successfully!"
      - name: Install dependencies and test build #modified and added pipe to manage indentation and execute all shell commands by using single run
        run: |
          npm ci
          npm test
          echo "Workflow practice completed successfully!"
      - name: Notify on completion
        if: always() # This ensures that the notification step runs regardless of the previous steps' success or failure
        run: |
          npm run notify
